version: '3.9'

services:
    db:
        image: postgres:13.0-alpine
        volumes:
            - .postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        container_name: smartdeals_db
        ports:
            - "5432:5432"
  
    web:
      build: .

      command: "python manage.py runserver 0.0.0.0:8000"

      ports:
        - 10555:8000
      volumes:
        - .:/usr/src/app/
        #this helps to pick all the changes in the code and push them to the container
      # env_file: .env
      environment:
          - POSTGRES_NAME=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
      depends_on:
        - db
      container_name: smartdeals

  
volumes:
    postgres_data: